# Generated by Django 3.0.8 on 2020-07-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('src', models.CharField(max_length=30)),
                ('extension', models.CharField(max_length=30)),
            ],
        ),
    ]
