# Generated by Django 3.0.8 on 2020-07-30 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('unit_size', models.IntegerField()),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.File')),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='MenuOnDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'menu_on_day',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('create_date', models.DateField()),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.File')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='StepMaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.File')),
            ],
            options={
                'db_table': 'step_making',
            },
        ),
        migrations.CreateModel(
            name='TypeEating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'type_eating',
            },
        ),
        migrations.CreateModel(
            name='StepMakingToRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_plane.Recipe')),
                ('step_making_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_plane.StepMaking')),
            ],
            options={
                'db_table': 'step_making_to_recipe',
            },
        ),
        migrations.CreateModel(
            name='StatisticCaloriesToMenuOnDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('menu_on_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_plane.MenuOnDay')),
            ],
            options={
                'db_table': 'statistic_calories_to_menu_on_day',
            },
        ),
        migrations.AddField(
            model_name='menuonday',
            name='recipe_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_plane.Recipe'),
        ),
        migrations.AddField(
            model_name='menuonday',
            name='type_eat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_plane.TypeEating'),
        ),
        migrations.AddField(
            model_name='menuonday',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IngredientToRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_plane.Ingredient')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_plane.Recipe')),
            ],
            options={
                'db_table': 'ingredient_to_recipe',
            },
        ),
    ]
